import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import { AppSidebar } from "@/components/elements/sidebar";
import { ThemeProvider } from "@/components/provider";
import { SidebarProvider } from "@/components/ui/sidebar";
import "./globals.css";

const font = Roboto({
  subsets: ["latin"],
  weight: ["400", "700"],
  variable: "--font-roboto",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${font.variable} ${font.variable} antialiased`}>
        <div id="app">
          <div id="csprclick-ui"></div>
        </div>
        <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
          <SidebarProvider>
            <AppSidebar />
            <main className="min-h-screen bg-background w-full">
              {children}
            </main>
          </SidebarProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
